# Fulfillments Binaries

[[bin]]
name = "autobahn-client"
path = "src/bin/autobahn-client.rs"
required-features = ["wtx/flate2", "wtx/optimization", "wtx/tokio", "wtx/web-socket-handshake"]

[[bin]]
name = "autobahn-server"
path = "src/bin/autobahn-server.rs"
required-features = ["wtx/flate2", "wtx/optimization", "wtx/pool", "wtx/tokio", "wtx/web-socket-handshake"]

[[bin]]
name = "h2spec-server"
path = "src/bin/h2spec-server.rs"
required-features = ["wtx/http2", "wtx/tokio"]

# Database Examples

[[example]]
name = "database-client-postgres"
path = "database-examples/database-client-postgres.rs"
required-features = ["wtx/postgres", "wtx/tokio"]

[[example]]
name = "database-client-postgres-composite-type"
path = "database-examples/database-client-postgres-composite-type.rs"
required-features = ["wtx/postgres", "wtx/tokio"]

[[example]]
name = "database-client-postgres-enum"
path = "database-examples/database-client-postgres-enum.rs"
required-features = ["wtx/postgres", "wtx/tokio"]

# Generic Examples

[[example]]
name = "client-api-framework"
path = "generic-examples/client-api-framework.rs"
required-features = ["wtx/client-api-framework", "wtx/tokio", "wtx/web-socket-handshake"]

[[example]]
name = "grpc-client"
path = "generic-examples/grpc-client.rs"
required-features = ["wtx/grpc", "wtx/quick-protobuf", "wtx/tokio"]

[[example]]
name = "grpc-server"
path = "generic-examples/grpc-server.rs"
required-features = ["wtx/grpc", "wtx/quick-protobuf", "wtx/tokio-rustls", "wtx/webpki-roots"]

[[example]]
name = "http-client-framework"
path = "generic-examples/http-client-framework.rs"
required-features = ["wtx/http-client-framework", "wtx/tokio"]

[[example]]
name = "http2-client"
path = "generic-examples/http2-client.rs"
required-features = ["wtx/http2", "wtx/tokio"]

[[example]]
name = "http2-server"
path = "generic-examples/http2-server.rs"
required-features = ["wtx/http2", "wtx/tokio-rustls"]

[[example]]
name = "pool"
path = "generic-examples/pool.rs"
required-features = ["wtx/pool"]

[[example]]
name = "web-socket-client"
path = "generic-examples/web-socket-client.rs"
required-features = ["wtx/tokio", "wtx/web-socket-handshake", "wtx/webpki-roots"]

[[example]]
name = "web-socket-server"
path = "generic-examples/web-socket-server.rs"
required-features = ["wtx/pool", "wtx/tokio-rustls", "wtx/web-socket-handshake"]

# HTTP Server Framework Examples

[[example]]
name = "http-server-framework"
path = "http-server-framework-examples/http-server-framework.rs"
required-features = ["wtx/http-server-framework", "wtx/pool", "wtx/postgres", "wtx/serde", "wtx/serde_json"]

[[example]]
name = "http-server-framework-cors"
path = "http-server-framework-examples/http-server-framework-cors.rs"
required-features = ["wtx/http-server-framework"]

[[example]]
name = "http-server-framework-redirect"
path = "http-server-framework-examples/http-server-framework-redirect.rs"
required-features = ["wtx/http-server-framework"]

[[example]]
name = "http-server-framework-session"
path = "http-server-framework-examples/http-server-framework-session.rs"
required-features = ["wtx/http-server-framework", "wtx/http-session", "wtx/pool", "wtx/postgres"]

[build-dependencies]
pb-rs = { default-features = false, version = "0.10" }

[dependencies]
argon2 = { default-features = false, version = "0.5" }
quick-protobuf = { default-features = false, version = "0.8" }
rand_chacha = { default-features = false, version = "0.3" }
rand_core = { default-features = false, features = ["getrandom"], version = "0.6" }
serde = { default-features = false, version = "1.0" }
serde_json = { default-features = false, features = ["alloc"], version = "1.0" }
tokio = { default-features = false, features = ["macros", "rt-multi-thread"], version = "1.0" }
tokio-rustls = { default-features = false, version = "0.26" }
wtx = { default-features = false, features = ["argon2", "grpc", "postgres"], path = "../wtx" }
wtx-macros = { default-features = false, path = "../wtx-macros" }

[features]
_tracing-tree = ["wtx/_tracing-tree"]

[package]
edition = "2021"
name = "wtx-instances"
publish = false
version = "0.0.0"