version: "3"

services:
    postgres_scram:
        environment:
            POSTGRES_DB: wtx
            POSTGRES_PASSWORD: wtx
        image: postgres:17
        ports:
            - 5432:5432
        volumes:
            - ./../.test-utils/postgres.sh:/docker-entrypoint-initdb.d/setup.sh