name: Bencher
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  benchmark_with_bencher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
      - name: Track Benchmarks with Bencher
        run: |
          set +e
          set +o pipefail

          function fun() {
            bencher run \
              --branch main \
              --err \
              --project wtx \
              --testbed ubuntu-latest \
              --token "${{ secrets.BENCHER_API_TOKEN }}" \
              "cargo bench --all-features"
            return $?
          }

          fun
          echo $?
          exit 0
          