name: Bencher
on:
  push:
    branches:
      - main

jobs:
  benchmark_with_bencher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
      - name: Track Benchmarks with Bencher
        continue-on-error: true
        run: |
          bencher run \
            --branch main \
            --err \
            --project wtx \
            --testbed ubuntu-latest \
            --token "${{ secrets.BENCHER_API_TOKEN }}" \
            "cargo bench --all-features"